### ISSUE TITLE
Code does not match comment above

### ISSUE THREAD

**Issue by FatesTimelines1337** [SadAugust/AutoTrimps#4]
https://github.com/SadAugust/AutoTrimps/blob/c7602a7d318e24e41970781b7402ca6577fa1a9c/modules/jobs.js#L289

This line was changed in commit 55f82f2, it does not match the above comment on line 287

**Comment by SadAugust** [comment]
Was changed to add the Miners ratio to Lumberjacks instead of Farmers due to a change made in patch 5.9 but forgot to update the comment.
